GET http://localhost:4000/rentings 

###
GET http://localhost:4000/products 

###
GET http://localhost:4000/rentings/count

###
GET http://localhost:4000/dashboard
###
GET http://localhost:4000/dashboard/rentprice